# creates namespace named "opssre-gateway-dev"
apiVersion: v1
kind: Namespace
metadata:
  name: opssre-gateway-dev
  annotations:
    configmanagement.gke.io/cluster-selector: opssre-dev-clusters
  labels:
    istio-injection: enabled
    environment-type: dev
